#!/bin/sh
#
# This script will build all components and run all tests.

make -C mpy-cross || exit $?
make -C leon-ex-minimal || exit $?
make -C leon-ex-tasks || exit $?
make -C leon-ex-manager || exit $?
make -C leon-for-tests || exit $?

(cd leon-tests && ./run-tests.sh CORE_BASICS/*.exp)
(cd leon-tests && ./run-tests.sh CORE_UNICODE/*.exp)
(cd leon-tests && ./run-tests.sh CORE_FLOAT/*.exp)
(cd leon-tests && ./run-tests.sh CORE_EXTMOD/*.exp)
(cd leon-tests && ./run-tests.sh CORE_MISC/*.exp)
(cd leon-tests && ./run-tests.sh CORE_MICROPYTHON/*.exp)
(cd leon-tests && ./run-tests.sh CORE_STRESS/*.exp)
(cd leon-tests && ./run-tests.sh spacebel_tickets/*.exp)
(cd leon-tests && ./run-tests.sh cpydiff/*.exp)
(cd leon-tests && ./run-tests.sh leon_t1/*.exp)
(cd leon-tests && ./run-tests.sh -t 2 leon_t2/*.exp)
(cd leon-tests && ./run-tests.sh -t 10 leon_t10/*.exp)
(cd leon-tests && ./run-tests.sh -o leon_perf/*.exp)
(cd leon-tests && ./run-tests-mpy-cross.sh mpy_cross/*.py)
(cd leon-ex-manager && ./run-test.sh)

# The OBCP example is not supported with Edisoft RTEMS 4.8
#make -C leon-obcp || exit $?
#(cd leon-obcp && ./run-test.sh)
