inf
inf
nan
ceil OverflowError
ceil OverflowError
ceil ValueError
floor OverflowError
floor OverflowError
floor ValueError
trunc OverflowError
trunc OverflowError
trunc ValueError
sqrt ValueError
0.0000
inf
sqrt ValueError
nan
inf
0.0000
nan
sin ValueError
sin ValueError
nan
cos ValueError
cos ValueError
nan
tan ValueError
tan ValueError
nan
asin ValueError
1.5708
asin ValueError
asin ValueError
asin ValueError
nan
acos ValueError
0.0000
acos ValueError
acos ValueError
acos ValueError
nan
1.5708
-1.5708
nan
inf
-inf
nan
inf
-inf
nan
inf
-inf
nan
0.0000
1.0000
pow ValueError
pow ValueError
0.0000
1.0000
inf
nan
nan
nan
1.2000
fmod ValueError
fmod ValueError
0.0000
fmod ValueError
fmod ValueError
nan
nan
nan
0.0000
0.0000
1.5708
0.7854
nan
nan
nan
0.0000
inf
inf
inf
nan
nan
