#include "leon-common/rtems_config_common.h"

#define MICROPY_RTEMS_NUM_TASKS (1)
#define MICROPY_RTEMS_HEAP_SIZE (48 * 1024)

#define MICROPY_RTEMS_TASK_ATTRIBUTES (RTEMS_APPLICATION_TASK | RTEMS_FLOATING_POINT)
#define MICROPY_RTEMS_STACK_SIZE (RTEMS_MINIMUM_STACK_SIZE * 2)

#define MAX_TLS_SIZE 0 //RTEMS_ALIGN_UP( 64, RTEMS_TASK_STORAGE_ALIGNMENT )
#define TASK_STORAGE_SIZE RTEMS_TASK_STORAGE_SIZE(MAX_TLS_SIZE + MICROPY_RTEMS_STACK_SIZE, MICROPY_RTEMS_TASK_ATTRIBUTES)
