#include "leon-common/rtems_config_common.h"

#define MICROPY_RTEMS_NUM_TASKS (10)
#define MICROPY_RTEMS_HEAP_SIZE (48 * 1024)
#define MICROPY_RTEMS_PYSTACK_WORD_SIZE (512)

#define CONFIGURE_MAXIMUM_TASKS (13)
#define CONFIGURE_MAXIMUM_SEMAPHORES (4)
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES (4)
#define CONFIGURE_EXTRA_TASK_STACKS (20 * RTEMS_MINIMUM_STACK_SIZE)

#define MICROPY_RTEMS_TASK_ATTRIBUTES (RTEMS_APPLICATION_TASK | RTEMS_FLOATING_POINT)
#define MICROPY_RTEMS_STACK_SIZE (RTEMS_MINIMUM_STACK_SIZE * 3)

#define MAX_TLS_SIZE RTEMS_ALIGN_UP(0, RTEMS_TASK_STORAGE_ALIGNMENT)
#define TASK_STORAGE_SIZE RTEMS_TASK_STORAGE_SIZE(MAX_TLS_SIZE + MICROPY_RTEMS_STACK_SIZE, MICROPY_RTEMS_TASK_ATTRIBUTES)
