UART A sent : OBCP program started
UART A sent : MicroPython worker task 0 started
UART A sent : MicroPython worker task 1 started
UART A sent : MicroPython worker task 2 started
UART A sent : MicroPython worker task 3 started
UART A sent : TM task started
UART A sent : TC task started
UART A sent : TEMP task started
UART A sent : GND task started
UART A sent : [ 0.003] TC wrote data to vm=0 off=0x0000 len=56
UART A sent : [ 0.007] TC wrote data to vm=0 off=0x0038 len=56
UART A sent : [ 0.010] TC wrote data to vm=0 off=0x0070 len=56
UART A sent : [ 0.013] TC wrote data to vm=0 off=0x00a8 len=56
UART A sent : [ 0.016] TC wrote data to vm=0 off=0x00e0 len=56
UART A sent : [ 0.020] TC wrote data to vm=0 off=0x0118 len=56
UART A sent : [ 0.024] TC wrote data to vm=0 off=0x0150 len=56
UART A sent : [ 0.027] TC wrote data to vm=0 off=0x0188 len=56
UART A sent : [ 0.030] TC wrote data to vm=0 off=0x01c0 len=56
UART A sent : [ 0.033] TC wrote data to vm=0 off=0x01f8 len=56
UART A sent : [ 0.038] TC wrote data to vm=0 off=0x0230 len=56
UART A sent : [ 0.041] TC wrote data to vm=0 off=0x0268 len=56
UART A sent : [ 0.044] TC wrote data to vm=0 off=0x02a0 len=56
UART A sent : [ 0.047] TC wrote data to vm=0 off=0x02d8 len=56
UART A sent : [ 0.050] TC wrote data to vm=0 off=0x0310 len=56
UART A sent : [ 0.054] GND: sent MPY_LOAD on TC queue
UART A sent : [ 0.057] TC wrote data to vm=0 off=0x0348 len=56
UART A sent : [ 0.060] TC wrote data to vm=0 off=0x0380 len=56
UART A sent : [ 0.063] TC wrote data to vm=0 off=0x03b8 len=56
UART A sent : [ 0.067] TC wrote data to vm=0 off=0x03f0 len=52
UART A sent : [ 0.178] GND: sent MPY_START on TC queue
UART A sent : [ 0.206] TC vm=0 len=1060 SHA256 PASS
UART A sent : THERM script started, using VM 0
UART A sent : THERM: initial temp_thres(0): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(1): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(2): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(3): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(4): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(5): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(6): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(7): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(8): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(9): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(10): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(11): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(12): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(13): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(14): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(15): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(16): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(17): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(18): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(19): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(20): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(21): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(22): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(23): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(24): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(25): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(26): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(27): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(28): [263.00, 283.00]
UART A sent : THERM: initial temp_thres(29): [263.00, 283.00]
UART A sent : [ 0.674] TC wrote data to vm=3 off=0x0000 len=56
UART A sent : [ 0.677] TC wrote data to vm=3 off=0x0038 len=56
UART A sent : [ 0.680] TC wrote data to vm=3 off=0x0070 len=56
UART A sent : [ 0.684] TC wrote data to vm=3 off=0x00a8 len=56
UART A sent : [ 0.687] TC wrote data to vm=3 off=0x00e0 len=56
UART A sent : [ 0.691] TC wrote data to vm=3 off=0x0118 len=56
UART A sent : [ 0.694] TC wrote data to vm=3 off=0x0150 len=56
UART A sent : [ 0.697] TC wrote data to vm=3 off=0x0188 len=56
UART A sent : [ 0.701] TC wrote data to vm=3 off=0x01c0 len=56
UART A sent : [ 0.704] TC wrote data to vm=3 off=0x01f8 len=56
UART A sent : [ 0.709] TC wrote data to vm=3 off=0x0230 len=56
UART A sent : [ 0.712] TC wrote data to vm=3 off=0x0268 len=56
UART A sent : [ 0.716] TC wrote data to vm=3 off=0x02a0 len=56
UART A sent : [ 0.719] TC wrote data to vm=3 off=0x02d8 len=56
UART A sent : [ 0.722] TC wrote data to vm=3 off=0x0310 len=56
UART A sent : [ 0.726] TC wrote data to vm=3 off=0x0348 len=56
UART A sent : [ 0.729] TC wrote data to vm=3 off=0x0380 len=56
UART A sent : [ 0.732] TC wrote data to vm=3 off=0x03b8 len=56
UART A sent : [ 0.736] TC wrote data to vm=3 off=0x03f0 len=56
UART A sent : [ 0.739] TC wrote data to vm=3 off=0x0428 len=56
UART A sent : [ 0.743] TC wrote data to vm=3 off=0x0460 len=56
UART A sent : [ 0.746] TC wrote data to vm=3 off=0x0498 len=56
UART A sent : [ 0.749] TC wrote data to vm=3 off=0x04d0 len=56
UART A sent : [ 0.753] TC wrote data to vm=3 off=0x0508 len=56
UART A sent : [ 0.756] TC wrote data to vm=3 off=0x0540 len=56
UART A sent : [ 0.760] TC wrote data to vm=3 off=0x0578 len=56
UART A sent : [ 0.764] TC wrote data to vm=3 off=0x05b0 len=56
UART A sent : [ 0.767] TC wrote data to vm=3 off=0x05e8 len=56
UART A sent : [ 0.770] TC wrote data to vm=3 off=0x0620 len=56
UART A sent : [ 0.773] TC wrote data to vm=3 off=0x0658 len=56
UART A sent : [ 0.777] TC wrote data to vm=3 off=0x0690 len=56
UART A sent : [ 0.781] TC wrote data to vm=3 off=0x06c8 len=56
UART A sent : [ 0.784] TC wrote data to vm=3 off=0x0700 len=56
UART A sent : [ 0.787] TC wrote data to vm=3 off=0x0738 len=56
UART A sent : [ 0.790] TC wrote data to vm=3 off=0x0770 len=56
UART A sent : [ 0.795] TC wrote data to vm=3 off=0x07a8 len=56
UART A sent : [ 0.798] TC wrote data to vm=3 off=0x07e0 len=56
UART A sent : [ 0.801] TC wrote data to vm=3 off=0x0818 len=56
UART A sent : [ 0.804] TC wrote data to vm=3 off=0x0850 len=56
UART A sent : [ 0.807] TC wrote data to vm=3 off=0x0888 len=56
UART A sent : [ 0.812] TC wrote data to vm=3 off=0x08c0 len=56
UART A sent : [ 0.815] TC wrote data to vm=3 off=0x08f8 len=56
UART A sent : [ 0.818] TC wrote data to vm=3 off=0x0930 len=56
UART A sent : [ 0.821] TC wrote data to vm=3 off=0x0968 len=56
UART A sent : [ 0.824] TC wrote data to vm=3 off=0x09a0 len=56
UART A sent : [ 0.828] GND: sent MPY_LOAD on TC queue
UART A sent : [ 0.830] TC wrote data to vm=3 off=0x09d8 len=56
UART A sent : [ 0.833] TC wrote data to vm=3 off=0x0a10 len=17
UART A sent : [ 0.983] GND: sent MPY_START on TC queue
UART A sent : [ 1.046] TC vm=3 len=2593 SHA256 PASS
UART A sent : POWER script started, using VM 3
UART A sent : POWER: initial volt_thres(0): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(1): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(2): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(3): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(4): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(5): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(6): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(7): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(8): [10.00, 13.00]
UART A sent : POWER: initial volt_thres(9): [10.00, 13.00]
UART A sent : POWER: initial curr_thres(0): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(1): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(2): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(3): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(4): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(5): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(6): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(7): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(8): [0.03, 0.04]
UART A sent : POWER: initial curr_thres(9): [0.03, 0.04]
UART A sent : [ 1.558] TM message: temperature(26) out of range; 283 outside [263, 283]
UART A sent : [ 1.564] TM message: temperature(27) out of range; 284 outside [263, 283]
UART A sent : [ 1.568] TM message: temperature(28) out of range; 284 outside [263, 283]
UART A sent : [ 1.573] TM message: temperature(29) out of range; 284 outside [263, 283]
UART A sent : [ 1.997] GND: send on TC queue: 4
UART A sent : POWER: change voltage threshold: 0 1.0 2.0
UART A sent : [ 2.123] TM message: voltage(0) out of range: 12.8 outside [1, 2]
UART A sent : [ 2.193] GND: send on TC queue: 5
UART A sent : POWER: change current threshold: 8 0.1 0.2
UART A sent : [ 2.255] TM message: voltage(0) out of range: 12.7 outside [1, 2]
UART A sent : [ 2.259] TM message: current(8) out of range; 0.0346 outside [0.1, 0.2]
UART A sent : [ 2.380] TM message: voltage(0) out of range: 12.7 outside [1, 2]
UART A sent : [ 2.384] TM message: current(8) out of range; 0.0346 outside [0.1, 0.2]
UART A sent : [ 2.500] TM message: voltage(0) out of range: 12.6 outside [1, 2]
UART A sent : [ 2.504] TM message: current(8) out of range; 0.0346 outside [0.1, 0.2]
UART A sent : [ 2.621] TM message: voltage(0) out of range: 12.6 outside [1, 2]
UART A sent : [ 2.625] TM message: current(8) out of range; 0.0346 outside [0.1, 0.2]
UART A sent : [ 2.693] GND: send on TC queue: 6
UART A sent : POWER: change current threshold: 8 0.0 0.5
UART A sent : [ 2.744] TM message: voltage(0) out of range: 12.5 outside [1, 2]
UART A sent : [ 2.868] TM message: voltage(0) out of range: 12.5 outside [1, 2]
UART A sent : [ 2.988] TM message: voltage(0) out of range: 12.4 outside [1, 2]
UART A sent : [ 2.993] GND: send on TC queue: 7
UART A sent : GND task ended
UART A sent : POWER: change voltage threshold: 0 12.0 14.0
UART A sent : [ 3.948] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [ 4.068] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 4.188] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 4.308] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 4.428] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 4.548] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [ 4.678] TM message: temperature(27) out of range; 263 outside [263, 283]
UART A sent : [ 4.682] TM message: temperature(28) out of range; 262 outside [263, 283]
UART A sent : [ 4.687] TM message: temperature(29) out of range; 262 outside [263, 283]
UART A sent : [ 4.691] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [ 4.798] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [ 4.918] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [ 5.038] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 5.158] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 5.278] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 5.398] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [ 5.518] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [ 7.744] TM message: temperature(27) out of range; 283 outside [263, 283]
UART A sent : [ 7.748] TM message: temperature(28) out of range; 284 outside [263, 283]
UART A sent : [ 7.753] TM message: temperature(29) out of range; 284 outside [263, 283]
UART A sent : [10.228] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [10.348] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [10.468] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [10.588] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [10.708] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [10.856] TM message: temperature(28) out of range; 263 outside [263, 283]
UART A sent : [10.861] TM message: temperature(29) out of range; 262 outside [263, 283]
UART A sent : [10.866] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [10.978] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [11.098] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [11.218] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [11.338] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [11.458] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [11.578] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [11.698] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [11.818] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [13.922] TM message: temperature(28) out of range; 283 outside [263, 283]
UART A sent : [13.927] TM message: temperature(29) out of range; 283 outside [263, 283]
UART A sent : [16.528] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [16.648] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [16.768] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [16.888] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.035] TM message: temperature(29) out of range; 263 outside [263, 283]
UART A sent : [17.040] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.158] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [17.278] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [17.398] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [17.518] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.638] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.758] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.878] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [17.998] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [18.040] TM message: temperature(29) out of range; 263 outside [263, 283]
UART A sent : [18.118] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [21.154] TM message: temperature(29) out of range; 283 outside [263, 283]
UART A sent : [22.838] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [22.958] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [23.078] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [23.214] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [23.338] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [23.458] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [23.578] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [23.698] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [23.818] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [23.938] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [24.058] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [24.178] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [24.221] TM message: temperature(28) out of range; 263 outside [263, 283]
UART A sent : [24.226] TM message: temperature(29) out of range; 262 outside [263, 283]
UART A sent : [24.298] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [27.337] TM message: temperature(27) out of range; 283 outside [263, 283]
UART A sent : [27.342] TM message: temperature(28) out of range; 283 outside [263, 283]
UART A sent : [27.347] TM message: temperature(29) out of range; 284 outside [263, 283]
UART A sent : [29.138] TM message: voltage(0) out of range: 12 outside [12, 14]
UART A sent : [29.258] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [29.394] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [29.518] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [29.638] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [29.758] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [29.878] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [29.998] TM message: voltage(0) out of range: 11.8 outside [12, 14]
UART A sent : [30.118] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [30.238] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : [30.358] TM message: voltage(0) out of range: 11.9 outside [12, 14]
UART A sent : TM task ended
