#include "leon-common/rtems_config_common.h"
#include "obcp.h"

#define CONFIGURE_MAXIMUM_TASKS (10)
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES (6)
#define CONFIGURE_MAXIMUM_POSIX_SEMAPHORES (VM_WORKER_NUM_TASKS * 2)
#define CONFIGURE_EXTRA_TASK_STACKS (20 * RTEMS_MINIMUM_STACK_SIZE)

#if RTEMS_5
#define CONFIGURE_MAXIMUM_SEMAPHORES (4)
#endif

#define MICROPY_RTEMS_TASK_ATTRIBUTES (RTEMS_APPLICATION_TASK | RTEMS_FLOATING_POINT)
#define MICROPY_RTEMS_STACK_SIZE (RTEMS_MINIMUM_STACK_SIZE * 2)

#define MAX_TLS_SIZE 0 //RTEMS_ALIGN_UP( 64, RTEMS_TASK_STORAGE_ALIGNMENT )
#define TASK_STORAGE_SIZE RTEMS_TASK_STORAGE_SIZE(MAX_TLS_SIZE + MICROPY_RTEMS_STACK_SIZE, MICROPY_RTEMS_TASK_ATTRIBUTES)
